spec:
  name: campo-marketplace
  region: nyc
  
  # Frontend - Static Site
  static_sites:
    - name: frontend
      source_dir: frontend
      build_command: npm install && npm run build
      output_dir: dist
      environment_slug: node-js
      routes:
        - path: /
      envs:
        - key: VITE_API_URL
          value: ${backend.PUBLIC_URL}
          scope: BUILD_TIME

  # Backend - Django API
  services:
    - name: backend
      source_dir: backend
      dockerfile_path: Dockerfile
      http_port: 8000
      instance_count: 1
      instance_size_slug: basic-xxs
      routes:
        - path: /api
      envs:
        - key: DEBUG
          value: "0"
        - key: DJANGO_ALLOWED_HOSTS
          value: ${APP_DOMAIN}
        - key: SECRET_KEY
          type: SECRET
          value: your-production-secret-key-change-this
        - key: DATABASE_URL
          type: SECRET
          value: ${db.DATABASE_URL}
        - key: CORS_ALLOWED_ORIGINS
          value: ${frontend.PUBLIC_URL}

  # PostgreSQL Database
  databases:
    - name: db
      engine: PG
      num_nodes: 1
      size: db-s-dev-database
      version: "15"
