spec:
  name: campo-marketplace
  region: nyc

  # Frontend - Static Site
  static_sites:
    - name: frontend
      github:
        repo: lagm1290/campo-marketplace
        branch: main
        deploy_on_push: true
      source_dir: frontend
      build_command: npm install && npm run build
      output_dir: dist
      catchall_document: index.html

  # Backend - Django API
  services:
    - name: backend
      github:
        repo: lagm1290/campo-marketplace
        branch: main
        deploy_on_push: true
      source_dir: backend
      environment_slug: python
      http_port: 8080
      instance_count: 1
      instance_size_slug: basic-xxs
      run_command: gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 2
      build_command: pip install -r requirements.txt
      envs:
        - key: DEBUG
          value: "0"
        - key: DJANGO_ALLOWED_HOSTS
          value: "*"
        - key: SECRET_KEY
          value: django-production-secret-key-change-me-please-2024
        - key: CORS_ALLOWED_ORIGINS
          value: "*"
