spec:
  name: campo-marketplace
  region: nyc

  # Frontend - Static Site (usando buildpack, no Docker)
  static_sites:
    - name: frontend
      github:
        repo: lagm1290/campo-marketplace
        branch: main
        deploy_on_push: true
      source_dir: frontend
      build_command: npm install && npm run build
      output_dir: dist
      catchall_document: index.html
      envs:
        - key: VITE_API_URL
          value: ${backend.PUBLIC_URL}/api
          scope: BUILD_TIME

  # Backend - Django API (usando Dockerfile)
  services:
    - name: backend
      github:
        repo: lagm1290/campo-marketplace
        branch: main
        deploy_on_push: true
      source_dir: backend
      dockerfile_path: Dockerfile
      http_port: 8000
      instance_count: 1
      instance_size_slug: basic-xxs
      envs:
        - key: DEBUG
          value: "0"
        - key: DJANGO_ALLOWED_HOSTS
          value: .ondigitalocean.app
        - key: SECRET_KEY
          type: SECRET
          value: django-production-secret-key-change-me-please-2024
        - key: CORS_ALLOWED_ORIGINS
          value: ${frontend.PUBLIC_URL}

  # PostgreSQL Database (opcional - usar si quieres persistencia)
  # databases:
  #   - name: db
  #     engine: PG
  #     num_nodes: 1
  #     size: db-s-dev-database
  #     version: "15"
